# CLUSTER SAMPLES WITH AN APPROPRIATE DISTANCE METRIC 

# IDENTIFY THE MOST APPROPRIATE NUMBER OF CLUSTERS (ELBOW OR GAP)

# COMPARE CLUSTERING RESULTS ON TWO DIFFERENT METHODS

# DISCUSS WHETHER WE CAN DESCRIBE OUR CLUSTERS IN TERMS OF THE COVARIATES: TIME.
# TREATMENT, REPLICATES