# PART 4: DISCRIMINANT ANALYSIS
source(file = "./R_SCRIPTS/Functions.R")

# LIBRARIES
library(tidyverse)
library(MASS)

# USING PC SCORES AS VARIABLES, GET A LINEAR DISCRIMINANT ANALYSIS RULE TO 
# DISCRIMINATE BETWEEN CELLS AT 12 HOURS (see file)




# HOW MANY PARAMETERS NEED TO BE ESTIMATED TO DERIVE THIS RULE? COMPARE IT TO 
# THE NUMBER OF SAMPLES


# RATIO OF SAMPLES TO PARAMETERS NUMBER SHOULD BE >1 - VERIFY


#DISCUSS CLASSIFICATION ERRORS